Create category page
QianyingLuo/PCMARKET_SERVICE pull request #11
Opened 2024-05-30 19:49 UTC by QianyingLuo

2024-05-31 08:24 UTC, devs-toni commented on index commented.txt
please remove this file

2024-05-31 09:35 UTC, QianyingLuo commented on index commented.txt
Done

2024-06-02 16:00 UTC, devs-toni requested changes

2024-06-02 16:00 UTC, devs-toni commented on src/controller/category.py
> +    smartphones = product_api.get_products_by_type("smartphone")
Change the functions naming

2024-06-02 16:55 UTC, QianyingLuo commented on src/controller/category.py
> +    smartphones = product_api.get_products_by_type("smartphone")
Done

2024-06-02 20:12 UTC, devs-toni approved these changes

2024-06-05 15:33 UTC, merged